#!/bin/bash

# curl must be installed for this script to work

if [ -z $1 ]
then
	echo "err: you haven't passed any arguments"
	echo "     type '$(basename $0) help', for help"
	exit 2
fi

out_dir=/tmp/c2-logs
mkdir -p $out_dir

function print_help {
	local base_name=$(basename $0)
	local c="\e[0m"  # clear colour
	local b="\e[94m"  # blue
	local bb="\e[1;94m"  # bold, blue
	local bfgb="\e[34;42m"  # blue foreground, green background (like ls dir/)
	echo -e "Usage: $bb$base_name$c$b COMMAND$c \n"
	echo -e "$bb$base_name$c$b help$c"
	echo -e "    This is what you've just typed to get this help message :)\n"
	echo -e "$bb$base_name$c$b clean$c"
	echo -e "    Cleans all files from output directory ($bfgb$out_dir$c)\n"
}

outfile_base=$out_dir/$(date +"%Y%m%d_%H%M%S")
outfile=$outfile_base-out.txt
logfile=$outfile_base-log.log

case $1 in
	clean)
		outfile_count=$(ls $out_dir | wc -l)
		if (( outfile_count == 0 ))
		then
			echo "already clean :D"
			exit 0
		fi

		echo "cleaning output directory..."
		rm $out_dir/*

		echo "checking for stragglers..."
		outfile_count=$(ls $out_dir | wc -l)

		echo "outfile count = $outfile_count"

		if (( outfile_count > 0 ))
		then
			echo "err: clean failed!"
			echo "     please navigate to $out_dir/ to check on the problem"
			exit 1
		fi
		echo "clean was successful!"
		exit 0
		;;

	# provide these options, but still prefer "help"
	-h | --help | h | help)
		print_help
		exit 0
		;;

	*)
		# for any other commands, those go to the server to be handled
		outfile=$outfile_base-response.txt
		logfile=$outfile_base-curl.log

		args=$(echo "$@" | tr ' ' ',')

		# N.B. curl -d makes POST requests
		curl -o $outfile -d "cli:$args" http://localhost:8200 &> $logfile
		;;
esac


if [ ! -f $outfile ]
then
	echo "oh noes, output file not created D:"
	if [ -f $logfile ]
	then
		echo "err: command failed, printing logs"

		cat $logfile

		exit 1
	fi
	echo "err: no logfile produced"
	exit 1
fi

cat $outfile
